# Generated by Django 4.1.7 on 2023-05-04 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 10, 53, 58, 341344), verbose_name='Date Published'),
        ),
    ]
