# Generated by Django 4.2.2 on 2023-10-25 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog_app', '0002_posts_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 10, 25, 15, 38, 16, 567009), verbose_name='Date Published')),
                ('write_up', models.TextField(verbose_name='Content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog_app.author')),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
