# Generated by Django 4.2.2 on 2023-10-25 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog_app', '0003_post_delete_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Writer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 17, 55, 12, 343154), verbose_name='Date Published'),
        ),
    ]
