# Generated by Django 4.2.2 on 2023-10-29 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog_app', '0004_post_author_name_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=300, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='my_blog_app.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 16, 13, 4, 567975), verbose_name='Date Published'),
        ),
    ]
