# Generated by Django 4.2.2 on 2023-10-29 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog_app', '0005_favorite_post_follows_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 16, 15, 58, 197257), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='my_blog_app.author'),
        ),
    ]
