# Generated by Django 4.2.2 on 2023-10-29 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog_app', '0006_alter_post_date_alter_post_follows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.RemoveField(
            model_name='post',
            name='follows',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 16, 21, 53, 216255), verbose_name='Date Published'),
        ),
        migrations.AddField(
            model_name='favorite_book',
            name='name',
            field=models.ManyToManyField(blank=True, to='my_blog_app.post'),
        ),
        migrations.AddField(
            model_name='favorite_book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog_app.author'),
        ),
    ]
