# Generated by Django 4.2.2 on 2023-10-29 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog_app', '0010_alter_favorite_book_user_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_book',
            name='name',
            field=models.ManyToManyField(blank=True, to='my_blog_app.favorite_book'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 17, 21, 3, 496009), verbose_name='Date Published'),
        ),
    ]
