# Generated by Django 4.2.2 on 2023-10-29 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog_app', '0011_alter_favorite_book_name_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_book',
            name='name',
            field=models.ManyToManyField(blank=True, to='my_blog_app.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 17, 22, 5, 228895), verbose_name='Date Published'),
        ),
    ]
