# Generated by Django 4.2.2 on 2023-10-30 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog_app', '0013_rename_name_favorite_book_name_of_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 11, 48, 23, 750750), verbose_name='Date Published'),
        ),
    ]
