# Generated by Django 4.2.2 on 2023-10-30 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog_app', '0014_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite_book',
            name='xxx',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 13, 30, 25, 57781), verbose_name='Date Published'),
        ),
    ]
